version: '3.9'

services:

  service-backend-mongodb:
    image: mongo:latest
    command: mongod
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes: 
      - ~/mongo/data:/data/db
    ports:
      - 27017:27017
      - 27888:27888
    restart: always

  service-backend-redis:
    image: redis:alpine
    volumes: 
      - ~/redis/data:/data/db
    ports:
      - 6379:6379
    restart: always

  service-api-gateway:
    build:
      context: .
      dockerfile: ApiGateway.Dockerfile 
    ports:
      - 2000:2000
      - 9229:9229
    env_file:
      - .development.env
    depends_on:
      - service-backend-mongodb
      - service-backend-redis
    restart: always

  service-consumer:
    build:
      context: .
      dockerfile: ServiceConsumer.Dockerfile 
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - .development.env
    depends_on:
      - service-backend-mongodb
      - service-backend-redis
    restart: always